### ISSUE TITLE
Crash (No OpenGL Context) after placing "Fire Ingot" from "HardCore Ore".

### ISSUE THREAD

**Issue by Zarepheth** [KidsDontPlay/Stackable#1]
Not only did my client crash immediately after placing the ingot, but it now crashes when I attempt to load the world!

Stack Trace:
```
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glMultMatrix(GL11.java:2338)
	at net.minecraftforge.client.ForgeHooksClient.multiplyCurrentGlMatrix(ForgeHooksClient.java:439)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:422)
	at mrriegel.stackable.client.ClientUtils.getBakedQuads(ClientUtils.java:376)
	at mrriegel.stackable.client.AnyPileModel.addQuads(AnyPileModel.java:23)
	at mrriegel.stackable.client.PileModel.func_188616_a(PileModel.java:59)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:158)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

```
For the full log: [paste.ee](https://paste.ee/p/lnF1k)

The initial crash occurred as I attempted to place 4 Fire Ingots on the ground (quark, marble bricks) while an Iron Golem was standing on the block.

I'm not entirely sure whether the Fire Ingot was directly from HardCore Ore or manufactured by JAOPCA from the Fire Ore block provided by HardCore Ore. At any rate, upon placement, my game crashed back to MultiMC. When I attempted to reload the world, I suffered the same error.

**Comment by KidsDontPlay** [comment]
Looks like you have a problem with your java installation or graphics driver.
google [this](https://www.google.com/search?q=No+OpenGL+context+found+in+the+current+thread+minecraft)

**Comment by Zarepheth** [comment]
Well, you may be correct. My nVidia drivers date back to 2017 October! That's despite using my video card manufacturer's tools to update to the latest stuff no more than 6 weeks ago (and maybe a few as 4 weeks).

So, this evening I'm updating my drivers from the nVidia website instead of MSI's website. I'll give my crashing world a try tomorrow evening and let you know how it went.

**Comment by Zarepheth** [comment]
No luck. Despite updating my MSI video card with nVidia's current drivers instead of the out-dated MSI drivers, I suffered the same crash while attempting to load the world.

**Comment by Zarepheth** [comment]
As an experiment, I installed the most recent Stackable mod. This time, the game froze at the point it was previously crashing. The HUD elements, including first person view of myself and what appeared to be particle effects around the probably location of an Iron Golem's feet, along with the highlight for a block all rendered before freezing.

None of the world blocks rendered.

Note: I had to update my Java installation before I could update my video drivers. 

Current Java version:
C:\WINDOWS\system32>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Increasing Java memory allocation from 8 GB to 10 GB did not stop the error - although the game felt like it loaded faster...

At this point, I think I'm going to have to say good-bye to that world and play with another.
