### ISSUE TITLE
Crash when retrieving stack

### ISSUE THREAD

**Issue by alex-fantastico** [KidsDontPlay/Stackable#9]
Crashing when I retrieve a whole stack more than two blocks high. Repeatable. 

https://paste.dimdev.org/kawuwocive.mccrash

**Comment by barttraeger** [comment]
Any update on this ?
Bug persists, retrieving stacks from a non-ingot pile with a height of over two blocks produces a crash and items are lost,,
with under or exactly two blocks height it works just fine.
Also happens when trying to interact with the pile via Refined Storage or similar mods.
Is this in any way fixable ? 
This is such a great mod!

Time: 2020-10-21 18:12:16 CEST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: toIndex = 24
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 24
    at java.util.ArrayList.subListRangeCheck(Unknown Source)
    at java.util.ArrayList.subList(Unknown Source)
    at mrriegel.stackable.tile.TilePile.itemList(TilePile.java:381)
    at mrriegel.stackable.PileInventory.onChange(PileInventory.java:133)
    at mrriegel.stackable.PileInventory.extractItem(PileInventory.java:58)
    at mrriegel.stackable.Events.leftclick(Events.java:70)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_919_Events_leftclick_LeftClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
    at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:141)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:693)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
